name: Synchronize the example with the template
on:
  schedule:
    # every 4 hours
    - cron: "0 */4 * * *"
  push:
  workflow_dispatch:

jobs:
  synchronize_example:
    runs-on: ubuntu-latest
    steps:
    - name: install cargo generate
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-generate
        version: latest

    - name: Create new example
      run: |
        cargo generate --git https://github.com/rust-github/template.git --name rust-gh-example

    - name: replace username
      run: |
        cd rust-gh-example
        sed -i 's#{\[username\]}#MyUsername#g' $(find . -type f -name '*.md' -o -name '*.yml' -o -name '*.toml')

    - name: Checkout old example
      uses: actions/checkout@v2
      with:
        repository: rust-github/rust-gh-example
        path: old_example

    - name: move sources from old to new example
      run: |
        echo "pwd:"
        pwd
        echo "ls -al:"
        ls -al
        rm rust-gh-example/src/main.rs
        cp old_example/src/* rust-gh-example/src/

    - name: update example
      run: |
        mkdir old_sources
        mv old_example/src/* old_sources
        cd old_example
        rm -rf * .gitignore .github/
        echo "ls ../rust-gh-example:"
        ls ../rust-gh-example
        echo "ls ../rust-gh-example/src:"
        ls ../rust-gh-example/src
        mv ../rust-gh-example/* ../rust-gh-example/.github ../rust-gh-example/.gitignore .
        echo "ls -al:"
        ls -al
        rm src/*
        mv ../old_sources/* src

    - name: commit example
      run: |
        cd old_example
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "automatic update" -m "from $GITHUB_REPOSITORY@$GITHUB_SHA"
          git push
        else
          echo "nothing to commit";
        fi
